name: Tests
on:
    push:
        branches:
        - '**'
        tags-ignore:
        - '**'
jobs:
    run:
        name: Run Isolated Tests
        runs-on: 'ubuntu-18.04'
        steps:
        -   name: Checkout source
            uses: actions/checkout@v2

        -   name: Run the automated tests with coverage report
            run: make isolated-test
