name: Tests
on:
    push:
        branches:
        - '**'
        tags-ignore:
        - '**'
jobs:
    run:
        name: Run Tests on ${{ matrix.operating-system }} with Go ${{ matrix.go-version }}
        services:
            redis:
                image: redis:6
                ports:
                - '6379:6379'
        strategy:
            matrix:
                operating-system: ['ubuntu-18.04']
                go-version: ['1.14']
        runs-on: ${{ matrix.operating-system }}
        steps:
        -   name: Set up Go ${{ matrix.go-version }}
            uses: actions/setup-go@v2
            with:
                go-version: ${{ matrix.go-version }}
        -   name: Checkout source
            uses: actions/checkout@v2

        -   name: Run the automated tests with coverage report
            run: make cover-all
